### ISSUE TITLE
Game does not run on iOS: WebGL: "both async and sync fetching of the wasm failed''

### ISSUE THREAD

**Issue by drikusroor** [pepemon-dao/pepemon-battle-degen#25]
## Reproduce
Visit https://play.pepemon.world/ on iOS

## Possible solution:
> Disabled the compression in Player settings - Publishing settings - Compression format and then it worked.
Perhaps the solution from above could help us? See also: https://forum.unity.com/threads/webgl-both-async-and-sync-fetching-of-the-wasm-failed-build-and-runs-works-fails-when-uploading.944400/

## Screenshot of problemo
![image](https://user-images.githubusercontent.com/8208970/185860223-3bf630a5-24bf-416d-8d49-2402148b2f8e.png)

**Comment by 0xdenkle** [comment]
Think this is fixed. Can you confirm?
