### ISSUE TITLE
Fix card drawing on each turn

### ISSUE THREAD

**Issue by benzo-diazepine** [pepemon-dao/pepemon-battle-degen#49]
In the card drawing does a modulo on the iterator used to select the cards, this was done to prevent a out of bounds access to an array in the function goForNewTurn in PepemonBattle.sol, however this makes the card drawing end up taking cards that might have already been used, or more cards than actually owned, which is NOT correct, this behavior was cloned into the game's client to be consistent.

There are some options as to how to solve this problem, in C# this is easy (eg.: store in an array the already-used cards), but in solidity the same solution (as done in C#) would consume too much Gas, so a different approach is necessary.

**Comment by pepem00n** [comment]
@benzo-diazepine is this still an on-going issue? in build .172?

**Comment by benzo-diazepine** [comment]
I believe not, I have not been able to reproduce it anymore after this commit https://github.com/pepemon-dao/pepemon-battle-degen/pull/48/commits/8234b78220205fab6653f43cc7c64930d760f832
