### ISSUE TITLE
failed to load card images because ssl certificate error

### ISSUE THREAD

**Issue by Zzurug** [pepemon-dao/pepemon-battle-degen#59]
when starting the game it tries to fetch the game cards but I get an SSL CA certificate error and there are no images shown  
tried with Firefox, Brave and Unity  
  
```shell 
Error while downloading card image 4: SSL CA certificate error
UnityEngine.Debug:LogWarning (object)
PepemonFactoryCardCache/<PreloadTokenImage>d__9:MoveNext () (at Assets/Scripts/UI/PepemonFactoryCardCache.cs:110)
System.Runtime.CompilerServices.AsyncMethodBuilderCore/MoveNextRunner:Run ()
Cysharp.Threading.Tasks.Internal.PooledDelegate`1<UnityEngine.AsyncOperation>:Run (UnityEngine.AsyncOperation) (at Library/PackageCache/com.cysharp.unitask@c7eedf85c7/Runtime/Internal/PooledDelegate.cs:46)
UnityEngine.AsyncOperation:InvokeCompletionEvent ()
  ```  
  
![grafik](https://user-images.githubusercontent.com/128488576/226720507-b8aedab4-540a-4bc5-a81a-0700e5a9157f.png)  
![grafik](https://user-images.githubusercontent.com/128488576/226720636-36eb8fdb-7d15-4178-beca-f10d136f16e8.png)
![grafik](https://user-images.githubusercontent.com/128488576/226720680-c2b21d6e-5587-4141-8806-a02d12e90102.png)

**Comment by 0xdenkle** [comment]
This is either an intermittent issue on IPFS, or you have some AV software that is blocking access.
Either way, not related to the game
